export const chats = [
  {
    avatar: "https://randomuser.me/api/portraits/men/32.jpg",
    name: "Faizan",
    _id: 1,
    groupChat: false,
    members: ["1", "2"],
  },
  {
    avatar: "https://randomuser.me/api/portraits/women/44.jpg",
    name: "Ayesha",
    _id: 2,
    groupChat: false,
    members: ["3", "4"],
  },
  {
    avatar: "https://randomuser.me/api/portraits/men/10.jpg",
    name: "Ahmed",
    _id: 3,
    groupChat: false,
    members: ["5", "6"],
  },
  {
    avatar: "https://randomuser.me/api/portraits/women/22.jpg",
    name: "Sara",
    _id: 4,
    groupChat: false,
    members: ["7", "8"],
  },
  {
    avatar: "https://randomuser.me/api/portraits/men/55.jpg",
    name: "Omar",
    _id: 5,
    groupChat: false,
    members: ["9", "10"],
  },
  {
    avatar: "https://randomuser.me/api/portraits/women/15.jpg",
    name: "Zara",
    _id: 6,
    groupChat: false,
    members: ["11", "12"],
  },
  {
    avatar: "https://randomuser.me/api/portraits/men/35.jpg",
    name: "Hassan",
    _id: 7,
    groupChat: true,
    members: ["13", "14", "15"],
  },
  {
    avatar: "https://randomuser.me/api/portraits/women/30.jpg",
    name: "Nadia",
    _id: 8,
    groupChat: true,
    members: ["16", "17", "18"],
  },
  {
    avatar: "https://randomuser.me/api/portraits/men/66.jpg",
    name: "Ali",
    _id: 9,
    groupChat: false,
    members: ["19", "20"],
  },
  {
    avatar: "https://randomuser.me/api/portraits/women/28.jpg",
    name: "Hina",
    _id: 10,
    groupChat: false,
    members: ["21", "22"],
  },
];
export const users = [
  {
    avatar: "https://randomuser.me/api/portraits/men/32.jpg",
    name: "Faizan",
    _id: 1,
  },
  {
    avatar: "https://randomuser.me/api/portraits/women/44.jpg",
    name: "Ayesha",
    _id: 2,
  },
  {
    avatar: "https://randomuser.me/api/portraits/men/10.jpg",
    name: "Ahmed",
    _id: 3,
  },
  {
    avatar: "https://randomuser.me/api/portraits/women/22.jpg",
    name: "Sara",
    _id: 4,
  },
  {
    avatar: "https://randomuser.me/api/portraits/men/55.jpg",
    name: "Omar",
    _id: 5,
  },
  {
    avatar: "https://randomuser.me/api/portraits/women/15.jpg",
    name: "Zara",
    _id: 6,
  },
  {
    avatar: "https://randomuser.me/api/portraits/men/35.jpg",
    name: "Hassan",
    _id: 7,
  },
  {
    avatar: "https://randomuser.me/api/portraits/women/30.jpg",
    name: "Nadia",
    _id: 8,
  },
  {
    avatar: "https://randomuser.me/api/portraits/men/66.jpg",
    name: "Ali",
    _id: 9,
  },
  {
    avatar: "https://randomuser.me/api/portraits/women/28.jpg",
    name: "Hina",
    _id: 10,
  },
];

export const notification = [
  {
    sender: {
      avatar: "https://randomuser.me/api/portraits/men/32.jpg",
      name: "Faizan",
    },
    time: "2023-08-14T09:00:00Z",
    status: "unread",
    isFriend: true,
    action: "shared the file",
    file: "ACME_guideline.pdf",
    buttons: true,
    group: "Project Alpha",
    _id: 1,
  },
  {
    sender: {
      avatar: "https://randomuser.me/api/portraits/women/44.jpg",
      name: "Ayesha",
    },
    time: "2023-08-13T14:30:00Z",
    status: "read",
    isFriend: false,
    _id: 2,
  },
  {
    sender: {
      avatar: "https://randomuser.me/api/portraits/men/10.jpg",
      name: "Ahmed",
    },
    time: "2023-08-13T10:15:00Z",
    status: "read",
    isFriend: false,
    _id: 3,
  },
  {
    sender: {
      avatar: "https://randomuser.me/api/portraits/women/22.jpg",
      name: "Sara",
    },
    time: "2023-08-12T16:00:00Z",
    status: "read",
    isFriend: true,
    action: "shared the file",
    file: "ACME_guideline.pdf",
    buttons: true,
    group: "HR Department",
    _id: 4,
  },
  {
    sender: {
      avatar: "https://randomuser.me/api/portraits/men/55.jpg",
      name: "Omar",
    },
    time: "2023-08-12T11:45:00Z",
    status: "read",
    isFriend: false,
    _id: 5,
  },
  {
    sender: {
      avatar: "https://randomuser.me/api/portraits/women/15.jpg",
      name: "Zara",
    },
    time: "2023-08-11T20:00:00Z",
    status: "read",
    isFriend: true,
    action: "shared the file",
    file: "ACME_guideline.pdf",
    buttons: true,
    group: "Marketing Team",
    _id: 6,
  },
  {
    sender: {
      avatar: "https://randomuser.me/api/portraits/men/35.jpg",
      name: "Hassan",
    },
    time: "2023-08-11T13:30:00Z",
    status: "read",
    isFriend: false,
    _id: 7,
  },
  {
    sender: {
      avatar: "https://randomuser.me/api/portraits/women/30.jpg",
      name: "Nadia",
    },
    time: "2023-08-10T09:00:00Z",
    status: "read",
    isFriend: true,
    // action: "shared the file",
    buttons: false,
    group: "HR Department",
    _id: 8,
  },
  {
    sender: {
      avatar: "https://randomuser.me/api/portraits/men/66.jpg",
      name: "Ali",
    },
    time: "2024-05-10T15:45:00Z",
    status: "read",
    isFriend: false,
    _id: 9,
  },
  {
    sender: {
      avatar: "https://randomuser.me/api/portraits/women/28.jpg",
      name: "Hina",
    },
    time: "2023-08-09T18:30:00Z",
    status: "read",
    isFriend: true,
    action: "shared the file",
    file: "ACME_guideline.pdf",
    buttons: true,
    group: "Marketing Team",
    _id: 10,
  },
];

export const messages = [
  {
    attachments: [
      {
        public_id: "asd",
        // url: "https://randomuser.me/api/portraits/women/28.jpg",
      },
    ],
    content: "Hello",
    _id: 2,
    sender: {
      _id: 2,
      name: "Shahid",
    },
    chat: "chatID",
    createdAt: "2024-08-15T18:30:00Z",
  },
  {
    attachments: [],
    content: "Hi",
    _id: 1,
    sender: {
      _id: 1,
      name: "Faizan",
    },
    chat: "chatID",
    createdAt: "2024-08-16T05:30:00Z",
  },
];

export const dashBoardData = {
  users: [
    {
      name: "Hina",
      avatar: "https://randomuser.me/api/portraits/women/28.jpg",
      _id: 1,
      username: "hina_786",
      friends: 20,
      groups: 2,
    },
    {
      name: "Arjun",
      avatar: "https://randomuser.me/api/portraits/men/15.jpg",
      _id: 2,
      username: "arjun_maverick",
      friends: 50,
      groups: 4,
    },
    {
      name: "Maya",
      avatar: "https://randomuser.me/api/portraits/women/35.jpg",
      _id: 3,
      username: "maya_zenith",
      friends: 32,
      groups: 3,
    },
    {
      name: "Ravi",
      avatar: "https://randomuser.me/api/portraits/men/44.jpg",
      _id: 4,
      username: "ravi_sharma",
      friends: 18,
      groups: 1,
    },
    {
      name: "Sara",
      avatar: "https://randomuser.me/api/portraits/women/12.jpg",
      _id: 5,
      username: "sara_love",
      friends: 25,
      groups: 2,
    },
    {
      name: "Naveen",
      avatar: "https://randomuser.me/api/portraits/men/30.jpg",
      _id: 6,
      username: "naveen_tech",
      friends: 40,
      groups: 5,
    },
    {
      name: "Leela",
      avatar: "https://randomuser.me/api/portraits/women/10.jpg",
      _id: 7,
      username: "leela_dancer",
      friends: 22,
      groups: 3,
    },
    {
      name: "Vikram",
      avatar: "https://randomuser.me/api/portraits/men/22.jpg",
      _id: 8,
      username: "vikram_king",
      friends: 15,
      groups: 2,
    },
    {
      name: "Ayesha",
      avatar: "https://randomuser.me/api/portraits/women/45.jpg",
      _id: 9,
      username: "ayesha_guru",
      friends: 35,
      groups: 4,
    },
    {
      name: "Rohan",
      avatar: "https://randomuser.me/api/portraits/men/25.jpg",
      _id: 10,
      username: "rohan_coder",
      friends: 28,
      groups: 1,
    },
    {
      name: "Meera",
      avatar: "https://randomuser.me/api/portraits/women/17.jpg",
      _id: 11,
      username: "meera_artist",
      friends: 50,
      groups: 5,
    },
    {
      name: "Kabir",
      avatar: "https://randomuser.me/api/portraits/men/36.jpg",
      _id: 12,
      username: "kabir_writer",
      friends: 42,
      groups: 4,
    },
    {
      name: "Sana",
      avatar: "https://randomuser.me/api/portraits/women/27.jpg",
      _id: 13,
      username: "sana_champ",
      friends: 30,
      groups: 3,
    },
    {
      name: "Raj",
      avatar: "https://randomuser.me/api/portraits/men/19.jpg",
      _id: 14,
      username: "raj_master",
      friends: 20,
      groups: 2,
    },
    {
      name: "Tara",
      avatar: "https://randomuser.me/api/portraits/women/5.jpg",
      _id: 15,
      username: "tara_star",
      friends: 18,
      groups: 1,
    },
    {
      name: "Amar",
      avatar: "https://randomuser.me/api/portraits/men/12.jpg",
      _id: 16,
      username: "amar_leader",
      friends: 33,
      groups: 4,
    },
    {
      name: "Anita",
      avatar: "https://randomuser.me/api/portraits/women/39.jpg",
      _id: 17,
      username: "anita_hustler",
      friends: 27,
      groups: 2,
    },
    {
      name: "Rakesh",
      avatar: "https://randomuser.me/api/portraits/men/40.jpg",
      _id: 18,
      username: "rakesh_boss",
      friends: 35,
      groups: 3,
    },
    {
      name: "Pooja",
      avatar: "https://randomuser.me/api/portraits/women/32.jpg",
      _id: 19,
      username: "pooja_explorer",
      friends: 45,
      groups: 5,
    },
    {
      name: "Siddharth",
      avatar: "https://randomuser.me/api/portraits/men/48.jpg",
      _id: 20,
      username: "sid_techguru",
      friends: 50,
      groups: 4,
    },
    {
      name: "Zara",
      avatar: "https://randomuser.me/api/portraits/women/41.jpg",
      _id: 21,
      username: "zara_queen",
      friends: 38,
      groups: 4,
    },
    {
      name: "Vivek",
      avatar: "https://randomuser.me/api/portraits/men/16.jpg",
      _id: 22,
      username: "vivek_warrior",
      friends: 26,
      groups: 2,
    },
    {
      name: "Isha",
      avatar: "https://randomuser.me/api/portraits/women/26.jpg",
      _id: 23,
      username: "isha_dreamer",
      friends: 29,
      groups: 3,
    },
    {
      name: "Ajay",
      avatar: "https://randomuser.me/api/portraits/men/35.jpg",
      _id: 24,
      username: "ajay_wizard",
      friends: 34,
      groups: 4,
    },
    {
      name: "Neha",
      avatar: "https://randomuser.me/api/portraits/women/2.jpg",
      _id: 25,
      username: "neha_sunshine",
      friends: 48,
      groups: 5,
    },
    {
      name: "Manoj",
      avatar: "https://randomuser.me/api/portraits/men/47.jpg",
      _id: 26,
      username: "manoj_knight",
      friends: 25,
      groups: 2,
    },
    {
      name: "Divya",
      avatar: "https://randomuser.me/api/portraits/women/13.jpg",
      _id: 27,
      username: "divya_blossom",
      friends: 39,
      groups: 4,
    },
    {
      name: "Kunal",
      avatar: "https://randomuser.me/api/portraits/men/37.jpg",
      _id: 28,
      username: "kunal_titan",
      friends: 27,
      groups: 3,
    },
    {
      name: "Ritu",
      avatar: "https://randomuser.me/api/portraits/women/11.jpg",
      _id: 29,
      username: "ritu_spark",
      friends: 36,
      groups: 4,
    },
    {
      name: "Ashok",
      avatar: "https://randomuser.me/api/portraits/men/7.jpg",
      _id: 30,
      username: "ashok_sage",
      friends: 31,
      groups: 3,
    },
    {
      name: "Priya",
      avatar: "https://randomuser.me/api/portraits/women/29.jpg",
      _id: 31,
      username: "priya_glow",
      friends: 43,
      groups: 5,
    },
    {
      name: "Dev",
      avatar: "https://randomuser.me/api/portraits/men/9.jpg",
      _id: 32,
      username: "dev_phoenix",
      friends: 28,
      groups: 3,
    },
    {
      name: "Radhika",
      avatar: "https://randomuser.me/api/portraits/women/20.jpg",
      _id: 33,
      username: "radhika_muse",
      friends: 40,
      groups: 4,
    },
    {
      name: "Gaurav",
      avatar: "https://randomuser.me/api/portraits/men/21.jpg",
      _id: 34,
      username: "gaurav_mentor",
      friends: 23,
      groups: 2,
    },
    {
      name: "Anjali",
      avatar: "https://randomuser.me/api/portraits/women/34.jpg",
      _id: 35,
      username: "anjali_goddess",
      friends: 47,
      groups: 5,
    },
    {
      name: "Varun",
      avatar: "https://randomuser.me/api/portraits/men/31.jpg",
      _id: 36,
      username: "varun_mastermind",
      friends: 24,
      groups: 3,
    },
    {
      name: "Pooja",
      avatar: "https://randomuser.me/api/portraits/women/43.jpg",
      _id: 37,
      username: "pooja_mystic",
      friends: 42,
      groups: 4,
    },
    {
      name: "Harish",
      avatar: "https://randomuser.me/api/portraits/men/33.jpg",
      _id: 38,
      username: "harish_savant",
      friends: 22,
      groups: 2,
    },
    {
      name: "Sonal",
      avatar: "https://randomuser.me/api/portraits/women/15.jpg",
      _id: 39,
      username: "sonal_visionary",
      friends: 44,
      groups: 5,
    },
    {
      name: "Rohan",
      avatar: "https://randomuser.me/api/portraits/men/26.jpg",
      _id: 40,
      username: "rohan_scholar",
      friends: 26,
      groups: 3,
    },
    {
      name: "Simran",
      avatar: "https://randomuser.me/api/portraits/women/31.jpg",
      _id: 41,
      username: "simran_beacon",
      friends: 41,
      groups: 4,
    },
    {
      name: "Raghav",
      avatar: "https://randomuser.me/api/portraits/men/18.jpg",
      _id: 42,
      username: "raghav_paladin",
      friends: 37,
      groups: 4,
    },
    {
      name: "Sneha",
      avatar: "https://randomuser.me/api/portraits/women/30.jpg",
      _id: 43,
      username: "sneha_dreamer",
      friends: 30,
      groups: 3,
    },
    {
      name: "Vijay",
      avatar: "https://randomuser.me/api/portraits/men/28.jpg",
      _id: 44,
      username: "vijay_triumph",
      friends: 25,
      groups: 2,
    },
    {
      name: "Shruti",
      avatar: "https://randomuser.me/api/portraits/women/25.jpg",
      _id: 45,
      username: "shruti_muse",
      friends: 46,
      groups: 5,
    },
    {
      name: "Sameer",
      avatar: "https://randomuser.me/api/portraits/men/3.jpg",
      _id: 46,
      username: "sameer_visionary",
      friends: 33,
      groups: 3,
    },
    {
      name: "Naina",
      avatar: "https://randomuser.me/api/portraits/women/16.jpg",
      _id: 47,
      username: "naina_hope",
      friends: 39,
      groups: 4,
    },
    {
      name: "Amit",
      avatar: "https://randomuser.me/api/portraits/men/24.jpg",
      _id: 48,
      username: "amit_hero",
      friends: 32,
      groups: 3,
    },
    {
      name: "Vidya",
      avatar: "https://randomuser.me/api/portraits/women/18.jpg",
      _id: 49,
      username: "vidya_light",
      friends: 50,
      groups: 5,
    },
    {
      name: "Arjun",
      avatar: "https://randomuser.me/api/portraits/men/20.jpg",
      _id: 50,
      username: "arjun_journey",
      friends: 28,
      groups: 3,
    },
  ],
};
